In [6]:
import plotly.express as px
df = px.data.gapminder().query("year == 2007").query("continent == 'Europe'")
df.loc[df['pop'] < 2.e6, 'country'] = 'Other countries' # Represent only large countries
fig = px.pie(df, values='pop', names='country', title='Population of European continent')
fig.show()

In [27]:
import pandas as pd
df=pd.read_csv('heart_disease_uci.csv')

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 920 entries, 0 to 919
Data columns (total 16 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   id        920 non-null    int64  
 1   age       916 non-null    float64
 2   gender    920 non-null    object 
 3   dataset   920 non-null    object 
 4   cp        916 non-null    object 
 5   trestbps  861 non-null    float64
 6   chol      890 non-null    float64
 7   fbs       830 non-null    object 
 8   restecg   918 non-null    object 
 9   thalch    865 non-null    float64
 10  exang     861 non-null    object 
 11  oldpeak   858 non-null    float64
 12  slope     611 non-null    object 
 13  ca        309 non-null    float64
 14  thal      434 non-null    object 
 15  num       920 non-null    int64  
dtypes: float64(6), int64(2), object(8)
memory usage: 115.1+ KB


In [25]:
import plotly.express as px
import pandas as pd

num_by_gender = df.groupby("gender", as_index=False)["num"].sum()


num_by_gender.loc[num_by_gender['num'] < 50, 'gender'] = 'Other'


fig = px.pie(num_by_gender, values='num', names='gender', 
             title="Sum of 'num' by Gender",color_discrete_sequence=px.colors.sequential.RdBu)
fig.show()


# Built-in functions

In [30]:
def qosh(x,y):
    return x+y

In [31]:
qosh(2,3)

5

In [33]:
qosh(2,3)+4- qosh(4,5)*4

-27

In [35]:
max(2,3)

3

In [36]:
def maks(x,y):
    if x>y:
        print('x eng katta son',x)
    elif x<y:
        print('y eng katta son',y)
    else:
        print('ikki son teng')

In [37]:
maks(3,5)

y eng katta son 5


In [38]:
maks(1,100)

y eng katta son 100


In [ ]:
#List

In [45]:
a=[1,4,2,3,5]

In [40]:
len(a)

5

In [41]:
min(a)

1

In [42]:
max(a)

5

In [43]:
sum(a)

15

In [46]:
sorted(a)

[1, 2, 3, 4, 5]

In [51]:
x=23.456
round(x,4)

23.456

In [ ]:
#map+lambda
def ikkilantir(x):
    return list(map(lambda x:x*2, [1,2,3,4,5]))

[2, 4, 6, 8, 10]

In [53]:
list(map(lambda x:x+2, [1,2,3,4,5]))

[3, 4, 5, 6, 7]

In [58]:
#filter+lambda
list(filter(lambda x:x>0 and   x%2!=0, [1,2,3,4,5,-3,-6]))

[1, 3, 5]

In [60]:
#Enumurate


for i , x in enumerate ([5,6,7,8,9,10]): print(i,x)

0 5
1 6
2 7
3 8
4 9
5 10


In [61]:
#Enumurate


for i , x in enumerate (['olma','behi','nok']): print(i,x)

0 olma
1 behi
2 nok


In [62]:
s=['olma','behi','nok']
for i in s:
    print(s)

['olma', 'behi', 'nok']
['olma', 'behi', 'nok']
['olma', 'behi', 'nok']


In [63]:
3 in (1,2,3)

True

In [64]:
3 not in (1,2,3)

False

In [66]:
# Numpy
import numpy as np
import pandas as pd

In [67]:
np.array([1,2,3])

array([1, 2, 3])

In [71]:
np.array([1,2,3]).mean()

2.0

In [73]:
np.array([1,2,3]).median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [74]:
a=np.array([1,2,3])

In [76]:
a.mean()

2.0

In [82]:
np.array([1,2,3]).reshape(3,1)

array([[1],
       [2],
       [3]])

In [83]:
np.array([1,2,3,4]).reshape(1,4)

array([[1, 2, 3, 4]])

In [84]:
np.array([1,2,3,4]).reshape(4,1)

array([[1],
       [2],
       [3],
       [4]])

In [85]:
np.array([1,2,3,4]).reshape(2,2)

array([[1, 2],
       [3, 4]])

In [88]:
np.random.randint(2)

1

In [89]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    object 
 3   smoker      244 non-null    object 
 4   day         244 non-null    object 
 5   time        244 non-null    object 
 6   size        244 non-null    int64  
dtypes: float64(2), int64(1), object(4)
memory usage: 13.5+ KB


In [90]:
df.describe()

,total_bill,tip,size
count,244.000000,244.000000,244.000000
mean,19.785943,2.998279,2.569672
std,8.902412,1.383638,0.951100
min,3.070000,1.000000,1.000000
25%,13.347500,2.000000,2.000000
50%,17.795000,2.900000,2.000000
75%,24.127500,3.562500,3.000000
max,50.810000,10.000000,6.000000


In [91]:
#Pandas
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    object 
 3   smoker      244 non-null    object 
 4   day         244 non-null    object 
 5   time        244 non-null    object 
 6   size        244 non-null    int64  
dtypes: float64(2), int64(1), object(4)
memory usage: 13.5+ KB


In [93]:
df.dropna(inplace=True)

In [ ]:
df.fillna()

In [ ]:
#train/test/split
#LabelEncoder